version: '2'
services:
    gpbat-app:
        image: gpbat
        external_links:
            - gpbat-mariadb:mariadb
            - gpbat-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/gpbat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    gpbat-mariadb:
        extends:
            file: mariadb.yml
            service: gpbat-mariadb
    gpbat-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gpbat-elasticsearch
